import {
  Controller,
  Get,
  Patch,
  Body,
  Param
} from '@nestjs/common';

import { QAGasProfile } from '@cedar-all/core-data';
import { GasProfilesService } from './gas-profiles.service';
import { ErrorInfo } from '@cedar-angular/api-interfaces';

@Controller('qaGasProfile')
export class GasProfilesController {
  constructor(private readonly gasProfilesService: GasProfilesService) {}

  @Get()
  getAllGasProfiles(): QAGasProfile[] {
    return this.gasProfilesService.getAllGasProfiles();
  }

  @Patch(':id')
  updateGasProfile(
    @Param('id') tagID: string,
    @Body('cylGasConc') cylGasConc: string,
    @Body('cylID') cylID: string,
    @Body('cylExpDate') cylExpDate: string,
    @Body('cylVendorID') cylVendorID: string,
    @Body('cylEpaGasTypeCode') cylEpaGasTypeCode: string,
    @Body('cylPressure') cylPressure: string,
    @Body('cylPressureUOM') cylPressureUOM: string,
    @Body('errorInfo') errorInfo: ErrorInfo[]
  ) {
    return this.gasProfilesService.updateGasProfile(
      tagID, 
      cylGasConc, 
      cylID, 
      cylExpDate, 
      cylVendorID, 
      cylEpaGasTypeCode, 
      cylPressure,
      cylPressureUOM,
      errorInfo
    );
  }
}


// [
//   {
//     "tagID": "110006050",
//     "desc": "NOx/L Cal Span Gas",
//     "unit": "1",
//     "cedarGasCode": "NOX",
//     "analyzerSpanType": "LOW",
//     "qaTestType": "CAL",
//     "gasLevel": "UPSCALE",
//     "uom": "ppm",
//     "instSpan": "10",
//     "allowableGasValueMin": "8",
//     "allowableGasValueMax": "10",
//     "cylGasConc": "12.3",
//     "cylID": "ABC56789",
//     "cylExpDate": "2019-08-01",
//     "cylVendorID": "A12017",
//     "cylEpaGasTypeCode": "NOX,CO,BALN",
//     "cylPressure": "1659",
//     "cylPressureUOM": "psi",
//     "errorInfo": [
//       {
//         "severity": "4",
//         "errorMsg": "Cylinder is expired"
//       },
//       {
//         "severity": "4",
//         "errorMsg": "Gas concentration (12.3 ppm NOx) is outside allowable range (8-10 ppm)"
//       }
//     ]
//   },
//   {
//     "tagID": "110006051",
//     "desc": "NOx/L CGA Low Gas",
//     "unit": "1",
//     "cedarGasCode": "NOX",
//     "analyzerSpanType": "LOW",
//     "qaTestType": "CGA",
//     "gasLevel": "LOW",
//     "uom": "ppm",
//     "instSpan": "10",
//     "allowableGasValueMin": "2",
//     "allowableGasValueMax": "3",
//     "cylGasConc": "2.57",
//     "cylID": "139482",
//     "cylExpDate": "2022-05-24",
//     "cylVendorID": "B22020",
//     "cylEpaGasTypeCode": "NOX,CO,BALN"
//   },
//   {
//     "tagID": "110006052",
//     "desc": "NOx/L CGA Mid Gas",
//     "unit": "1",
//     "cedarGasCode": "NOX",
//     "analyzerSpanType": "LOW",
//     "qaTestType": "CGA",
//     "gasLevel": "MID",
//     "uom": "ppm",
//     "instSpan": "10",
//     "allowableGasValueMin": "5",
//     "allowableGasValueMax": "6",
//     "cylGasConc": "5.84",
//     "cylID": "CC834059",
//     "cylExpDate": "2022-05-27",
//     "cylVendorID": "B22020",
//     "cylEpaGasTypeCode": "NOX,CO,BALN"
//   },
//   {
//     "tagID": "110006060",
//     "desc": "NOx/H Cal Span Gas",
//     "unit": "1",
//     "cedarGasCode": "NOX",
//     "analyzerSpanType": "HIGH",
//     "qaTestType": "CAL",
//     "gasLevel": "UPSCALE",
//     "uom": "ppm",
//     "instSpan": "100",
//     "allowableGasValueMin": "80",
//     "allowableGasValueMax": "100",
//     "cylGasConc": "87.3",
//     "cylID": "CC832093SS",
//     "cylExpDate": "2023-10-03",
//     "cylVendorID": "F32019",
//     "cylEpaGasTypeCode": "NOX,CO,BALN",
//     "cylPressure": "1659",
//     "cylPressureUOM": "psi"
//   },
//   {
//     "tagID": "110006061",
//     "desc": "NOx/H Linearity Low Gas",
//     "unit": "1",
//     "cedarGasCode": "NOX",
//     "analyzerSpanType": "HIGH",
//     "qaTestType": "LIN",
//     "gasLevel": "LOW",
//     "uom": "ppm",
//     "instSpan": "100",
//     "allowableGasValueMin": "20",
//     "allowableGasValueMax": "30",
//     "cylGasConc": "24.1",
//     "cylID": "856730BB",
//     "cylExpDate": "2024-04-16",
//     "cylVendorID": "B22020",
//     "cylEpaGasTypeCode": "NOX,CO,BALN"
//   },
//   {
//     "tagID": "110006062",
//     "desc": "NOx/H Linearity Mid Gas",
//     "unit": "1",
//     "cedarGasCode": "NOX",
//     "analyzerSpanType": "HIGH",
//     "qaTestType": "LIN",
//     "gasLevel": "MID",
//     "uom": "ppm",
//     "instSpan": "100",
//     "allowableGasValueMin": "50",
//     "allowableGasValueMax": "60",
//     "cylGasConc": "56.8",
//     "cylID": "270194ALM",
//     "cylExpDate": "2024-04-13",
//     "cylVendorID": "B22020",
//     "cylEpaGasTypeCode": "NOX,CO,BALN"
//   },
//   {
//     "tagID": "110006063",
//     "desc": "NOx/H Linearity High Gas",
//     "unit": "1",
//     "cedarGasCode": "NOX",
//     "analyzerSpanType": "HIGH",
//     "qaTestType": "LIN",
//     "gasLevel": "HIGH",
//     "uom": "ppm",
//     "instSpan": "100",
//     "allowableGasValueMin": "80",
//     "allowableGasValueMax": "100",
//     "cylGasConc": "87.3",
//     "cylID": "CC832093SS",
//     "cylExpDate": "2023-10-03",
//     "cylVendorID": "F32019",
//     "cylEpaGasTypeCode": "NOX,CO,BALN"
//   },
//   {
//     "tagID": "114006050",
//     "desc": "CO/L Cal Span Gas",
//     "unit": "1",
//     "cedarGasCode": "CO",
//     "analyzerSpanType": "LOW",
//     "qaTestType": "CAL",
//     "gasLevel": "UPSCALE",
//     "uom": "ppm",
//     "instSpan": "20",
//     "allowableGasValueMin": "16",
//     "allowableGasValueMax": "20",
//     "cylGasConc": "17.2",
//     "cylID": "ABC56789",
//     "cylExpDate": "2019-08-01",
//     "cylVendorID": "A12017",
//     "cylEpaGasTypeCode": "NOX,CO,BALN",
//     "cylPressure": "1659",
//     "cylPressureUOM": "psi",
//     "errorInfo": {
//       "severity": "4",
//       "errorMsg": "Cylinder is expired"
//     }
//   },
//   {
//     "tagID": "114006051",
//     "desc": "CO/L CGA Low Gas",
//     "unit": "1",
//     "cedarGasCode": "CO",
//     "analyzerSpanType": "LOW",
//     "qaTestType": "CGA",
//     "gasLevel": "LOW",
//     "uom": "ppm",
//     "instSpan": "10",
//     "allowableGasValueMin": "4",
//     "allowableGasValueMax": "6",
//     "cylGasConc": "5.66",
//     "cylID": "139482",
//     "cylExpDate": "2022-05-24",
//     "cylVendorID": "B22020",
//     "cylEpaGasTypeCode": "NOX,CO,BALN"
//   },
//   {
//     "tagID": "114006052",
//     "desc": "CO/L CGA Mid Gas",
//     "unit": "1",
//     "cedarGasCode": "CO",
//     "analyzerSpanType": "LOW",
//     "qaTestType": "CGA",
//     "gasLevel": "MID",
//     "uom": "ppm",
//     "instSpan": "10",
//     "allowableGasValueMin": "10",
//     "allowableGasValueMax": "12",
//     "cylGasConc": "10.7",
//     "cylID": "CC834059",
//     "cylExpDate": "2022-05-27",
//     "cylVendorID": "B22020",
//     "cylEpaGasTypeCode": "NOX,CO,BALN"
//   },
//   {
//     "tagID": "114006060",
//     "desc": "CO/H Cal Span Gas",
//     "unit": "1",
//     "cedarGasCode": "CO",
//     "analyzerSpanType": "HIGH",
//     "qaTestType": "CAL",
//     "gasLevel": "UPSCALE",
//     "uom": "ppm",
//     "instSpan": "200",
//     "allowableGasValueMin": "160",
//     "allowableGasValueMax": "200",
//     "cylGasConc": "189.0",
//     "cylID": "CC832093SS",
//     "cylExpDate": "2023-10-03",
//     "cylVendorID": "F32019",
//     "cylEpaGasTypeCode": "NOX,CO,BALN",
//     "cylPressure": "1659",
//     "cylPressureUOM": "psi"
//   },
//   {
//     "tagID": "114006061",
//     "desc": "CO/H CGA Low Gas",
//     "unit": "1",
//     "cedarGasCode": "CO",
//     "analyzerSpanType": "HIGH",
//     "qaTestType": "CGA",
//     "gasLevel": "LOW",
//     "uom": "ppm",
//     "instSpan": "200",
//     "allowableGasValueMin": "40",
//     "allowableGasValueMax": "60",
//     "cylGasConc": "48.1",
//     "cylID": "856730BB",
//     "cylExpDate": "2024-04-16",
//     "cylVendorID": "B22020",
//     "cylEpaGasTypeCode": "NOX,CO,BALN"
//   },
//   {
//     "tagID": "114006062",
//     "desc": "CO/H CGA Mid Gas",
//     "unit": "1",
//     "cedarGasCode": "CO",
//     "analyzerSpanType": "HIGH",
//     "qaTestType": "CGA",
//     "gasLevel": "MID",
//     "uom": "ppm",
//     "instSpan": "200",
//     "allowableGasValueMin": "100",
//     "allowableGasValueMax": "120",
//     "cylGasConc": "106",
//     "cylID": "270194ALM",
//     "cylExpDate": "2024-04-13",
//     "cylVendorID": "B22020",
//     "cylEpaGasTypeCode": "NOX,CO,BALN"
//   },
//   {
//     "tagID": "124006061",
//     "desc": "O2 Linearity Low Gas",
//     "unit": "1",
//     "cedarGasCode": "O2",
//     "analyzerSpanType": "HIGH",
//     "qaTestType": "LIN",
//     "gasLevel": "LOW",
//     "uom": "%O2",
//     "instSpan": "21",
//     "allowableGasValueMin": "4.2",
//     "allowableGasValueMax": "6",
//     "cylGasConc": "5.38",
//     "cylID": "CC092481",
//     "cylExpDate": "2022-01-24",
//     "cylVendorID": "B22019",
//     "cylEpaGasTypeCode": "O2,BALN"
//   },
//   {
//     "tagID": "124006062",
//     "desc": "O2 Linearity Mid Gas",
//     "unit": "1",
//     "cedarGasCode": "O2",
//     "analyzerSpanType": "HIGH",
//     "qaTestType": "LIN",
//     "gasLevel": "MID",
//     "uom": "%O2",
//     "instSpan": "21",
//     "allowableGasValueMin": "10.5",
//     "allowableGasValueMax": "12",
//     "cylGasConc": "11.4",
//     "cylID": "CC459201",
//     "cylExpDate": "2022-11-29",
//     "cylVendorID": "B22020",
//     "cylEpaGasTypeCode": "O2,BALN"
//   },
//   {
//     "tagID": "124006063",
//     "desc": "O2 Linearity High Gas",
//     "unit": "1",
//     "cedarGasCode": "O2",
//     "analyzerSpanType": "HIGH",
//     "qaTestType": "LIN",
//     "gasLevel": "HIGH",
//     "uom": "%O2",
//     "instSpan": "21",
//     "allowableGasValueMin": "16.8",
//     "allowableGasValueMax": "21",
//     "cylGasConc": "18.7",
//     "cylID": "ALM3459",
//     "cylExpDate": "2023-06-24",
//     "cylVendorID": "F32020",
//     "cylEpaGasTypeCode": "O2,BALN"
//   },
//   {
//     "tagID": "310006050",
//     "desc": "NOx Cal Span Gas",
//     "unit": "3",
//     "cedarGasCode": "NOX",
//     "analyzerSpanType": "LOW",
//     "qaTestType": "CAL",
//     "gasLevel": "UPSCALE",
//     "uom": "ppm",
//     "instSpan": "200",
//     "allowableGasValueMin": "160",
//     "allowableGasValueMax": "200",
//     "cylGasConc": "161",
//     "cylID": "RR9830291",
//     "cylExpDate": "2022-04-19",
//     "cylVendorID": "A12019",
//     "cylEpaGasTypeCode": "NOX,BALN"
//   },
//   {
//     "tagID": "310006051",
//     "desc": "NOx CGA Low Gas",
//     "unit": "3",
//     "cedarGasCode": "NOX",
//     "analyzerSpanType": "LOW",
//     "qaTestType": "CGA",
//     "gasLevel": "LOW",
//     "uom": "ppm",
//     "instSpan": "200",
//     "allowableGasValueMin": "40",
//     "allowableGasValueMax": "60",
//     "cylGasConc": "51.9",
//     "cylID": "YY167901",
//     "cylExpDate": "2022-03-22",
//     "cylVendorID": "B22020",
//     "cylEpaGasTypeCode": "NOX,BALN"
//   },
//   {
//     "tagID": "310006052",
//     "desc": "NOx CGA Mid Gas",
//     "unit": "3",
//     "cedarGasCode": "NOX",
//     "analyzerSpanType": "LOW",
//     "qaTestType": "CGA",
//     "gasLevel": "MID",
//     "uom": "ppm",
//     "instSpan": "200",
//     "allowableGasValueMin": "100",
//     "allowableGasValueMax": "120",
//     "cylGasConc": "113",
//     "cylID": "EF387290",
//     "cylExpDate": "2022-06-03",
//     "cylVendorID": "B22020",
//     "cylEpaGasTypeCode": "NOX,BALN"
//   },
//   {
//     "tagID": "314006050",
//     "desc": "CO Cal Span Gas",
//     "unit": "3",
//     "cedarGasCode": "CO",
//     "analyzerSpanType": "LOW",
//     "qaTestType": "CAL",
//     "gasLevel": "UPSCALE",
//     "uom": "ppm",
//     "instSpan": "500",
//     "allowableGasValueMin": "400",
//     "allowableGasValueMax": "500",
//     "cylGasConc": "470",
//     "cylID": "FF98374220",
//     "cylExpDate": "2023-02-13",
//     "cylVendorID": "A12020",
//     "cylEpaGasTypeCode": "CO,BALN"
//   },
//   {
//     "tagID": "314006051",
//     "desc": "CO CGA Low Gas",
//     "unit": "3",
//     "cedarGasCode": "CO",
//     "analyzerSpanType": "LOW",
//     "qaTestType": "CGA",
//     "gasLevel": "LOW",
//     "uom": "ppm",
//     "instSpan": "500",
//     "allowableGasValueMin": "100",
//     "allowableGasValueMax": "150",
//     "cylGasConc": "118",
//     "cylID": "FF029310",
//     "cylExpDate": "2023-05-01",
//     "cylVendorID": "B22020",
//     "cylEpaGasTypeCode": "CO,BALN"
//   },
//   {
//     "tagID": "314006052",
//     "desc": "CO CGA Mid Gas",
//     "unit": "3",
//     "cedarGasCode": "CO",
//     "analyzerSpanType": "LOW",
//     "qaTestType": "CGA",
//     "gasLevel": "MID",
//     "uom": "ppm",
//     "instSpan": "500",
//     "allowableGasValueMin": "250",
//     "allowableGasValueMax": "300",
//     "cylGasConc": "269",
//     "cylID": "980293",
//     "cylExpDate": "2022-10-09",
//     "cylVendorID": "B22020",
//     "cylEpaGasTypeCode": "CO,BALN"
//   },
//   {
//     "tagID": "324006060",
//     "desc": "CO2 Cal Span Gas",
//     "unit": "3",
//     "cedarGasCode": "CO2",
//     "analyzerSpanType": "HIGH",
//     "qaTestType": "CAL",
//     "gasLevel": "UPSCALE",
//     "uom": "%CO2",
//     "instSpan": "20",
//     "allowableGasValueMin": "16",
//     "allowableGasValueMax": "20",
//     "cylGasConc": "17.3",
//     "cylID": "CC082034",
//     "cylExpDate": "2023-06-24",
//     "cylVendorID": "B22020",
//     "cylEpaGasTypeCode": "CO2,BALN"
//   },
//   {
//     "tagID": "324006061",
//     "desc": "CO2 CGA Low Gas",
//     "unit": "3",
//     "cedarGasCode": "CO2",
//     "analyzerSpanType": "HIGH",
//     "qaTestType": "CGA",
//     "gasLevel": "LOW",
//     "uom": "%CO2",
//     "instSpan": "20",
//     "allowableGasValueMin": "5",
//     "allowableGasValueMax": "8",
//     "cylGasConc": "6.81",
//     "cylID": "CC762039",
//     "cylExpDate": "2023-06-24",
//     "cylVendorID": "B22020",
//     "cylEpaGasTypeCode": "CO2,BALN"
//   },
//   {
//     "tagID": "324006062",
//     "desc": "CO2 CGA Mid Gas",
//     "unit": "3",
//     "cedarGasCode": "CO2",
//     "analyzerSpanType": "HIGH",
//     "qaTestType": "CGA",
//     "gasLevel": "MID",
//     "uom": "%CO2",
//     "instSpan": "20",
//     "allowableGasValueMin": "10",
//     "allowableGasValueMax": "14",
//     "cylGasConc": "12.8",
//     "cylID": "FF732107",
//     "cylExpDate": "2022-11-28",
//     "cylVendorID": "B22020",
//     "cylEpaGasTypeCode": "CO2,BALN"
//   }
// ]
